// FontAwesome configuration ottimizzata per la nitidezza
import { library, config } from '@fortawesome/fontawesome-svg-core';
import {
  faExternalLinkAlt,
  faInfoCircle,
  faArrowRight,
  faSearch,
  faBars,
  faEnvelope,
  faPhone,
  faMapMarkerAlt,
  faClock,
  faCheck,
  faChevronRight,
  faChevronLeft,
  faChevronDown,
  faChevronUp,
  // Icone per i badge di tipo
  faNewspaper,
  faUser,
  faQuoteLeft,
  // Icone per le statistiche
  faGlobeEurope,
  faCalendarCheck,
  faUserTie,
  faEuroSign,
  // Icone per media coverage
  faTrophy,
  faBook,
  faMedal,
  faRocket,
  faAward,
  // Icone per WhyChooseUs
  faGlobe,
  faCertificate,
  faHandshake,
  faBolt,
  // Icone social
  faFacebookF,
  faInstagram,
  faLinkedin,
  faLinkedinIn,
  faTiktok,
  faTwitter,
  faWhatsapp,
  faYoutube,
  // Icone varie
  faArrowDown,
  faArrowLeft,
  faBalanceScale,
  faBuilding,
  faCalculator,
  faCalendar,
  faChartLine,
  faChartPie,
  faCheckCircle,
  faCog,
  faCogs,
  faCookieBite,
  faDownload,
  faEllipsisH,
  faExclamationCircle,
  faExclamationTriangle,
  faExpand,
  faFileInvoiceDollar,
  faFolderOpen,
  faHandHoldingUsd,
  faHeadset,
  faHouseUser,
  faIdCard,
  faImage,
  faLaptopCode,
  faLeaf,
  faLightbulb,
  faPaperPlane,
  faPercentage,
  faPhoneAlt,
  faShareAlt,
  faShieldAlt,
  faShoppingCart,
  faStar,
  faSuitcaseRolling,
  faTimes,
  faUserCircle,
  faUsers,
  faVenus
} from '@fortawesome/free-solid-svg-icons';
import {
  faFacebookF,
  faInstagram,
  faLinkedin,
  faLinkedinIn,
  faTiktok,
  faTwitter,
  faWhatsapp,
  faYoutube
} from '@fortawesome/free-brands-svg-icons';

// Configurazione ottimizzata per il rendering
config.autoAddCss = true; // Assicurarsi che il CSS sia aggiunto automaticamente
config.searchPseudoElements = true; // Cerca anche gli pseudo-elementi per una migliore compatibilità
config.observeMutations = true; // Osserva le mutazioni del DOM per aggiornare le icone dinamicamente
config.keepOriginalSource = false; // Rimuovere il codice sorgente originale per ottimizzare le prestazioni

// Precaricamento delle icone più utilizzate
const preloadedIcons = [
  faExternalLinkAlt,
  faInfoCircle,
  faArrowRight,
  faNewspaper,
  faUser,
  faQuoteLeft
];

// Aggiunta di tutte le icone alla libreria
library.add(
  faExternalLinkAlt,
  faInfoCircle,
  faArrowRight,
  faSearch,
  faBars,
  faEnvelope,
  faPhone,
  faMapMarkerAlt,
  faClock,
  faCheck,
  faChevronRight,
  faChevronLeft,
  faChevronDown,
  faChevronUp,
  faNewspaper,
  faUser,
  faQuoteLeft,
  // Icone per le statistiche
  faGlobeEurope,
  faCalendarCheck,
  faUserTie,
  faEuroSign,
  // Icone per media coverage
  faTrophy,
  faBook,
  faMedal,
  faRocket,
  faAward,
  // Icone per WhyChooseUs
  faGlobe,
  faCertificate,
  faHandshake,
  faBolt,
  // Icone social
  faFacebookF,
  faInstagram,
  faLinkedin,
  faLinkedinIn,
  faTiktok,
  faTwitter,
  faWhatsapp,
  faYoutube,
  // Icone varie
  faArrowDown,
  faArrowLeft,
  faBalanceScale,
  faBuilding,
  faCalculator,
  faCalendar,
  faChartLine,
  faChartPie,
  faCheckCircle,
  faCog,
  faCogs,
  faCookieBite,
  faDownload,
  faEllipsisH,
  faExclamationCircle,
  faExclamationTriangle,
  faExpand,
  faFileInvoiceDollar,
  faFolderOpen,
  faHandHoldingUsd,
  faHeadset,
  faHouseUser,
  faIdCard,
  faImage,
  faLaptopCode,
  faLeaf,
  faLightbulb,
  faPaperPlane,
  faPercentage,
  faPhoneAlt,
  faShareAlt,
  faShieldAlt,
  faShoppingCart,
  faStar,
  faSuitcaseRolling,
  faTimes,
  faUserCircle,
  faUsers,
  faVenus
);

// Esporta sia la libreria che le icone precaricate
export { preloadedIcons };
export default library;
